import "./globals.css"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import { Navigation, Footer } from '@/components/navfooter'
import React from 'react';

export const metadata = {
  title: "CRUD Med MongoDB & NextJS",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html className="bg-white" lang="en">
      <body className="relative">
        <main>
          <Navigation/>
          {children}
          <Footer/>
        </main>
        <ToastContainer
          position="bottom-center"
          autoClose={5000}
          hideProgressBar={true}
          stacked={true}
          newestOnTop={true}
          draggable={true}
          closeOnClick={true}
          closeButton={false}
          theme="colored"
        />
      </body>
    </html>
  )
}
